/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      backgroundImage: {},
      transitionProperty: {
        width: 'width',
        height: 'height',
        spacing: 'margin, padding',
        border: 'border-color',
        color: 'color',
        bg: 'background-color',
        opacity: 'opacity',
        transform: 'transform',
      },

      colors: {
        white: 'var(--white)',
        primary: 'var(--primary)',
        secondary: 'var(--secondary)',
        background: 'var(--background)',
        red: 'var(--red)',
        lightRed: 'var(  --light-red)',
        blackColor: 'var(--black)',
        lightBlack: 'var(--light-black)',
        grayColor: 'var(--gray)',
        grayColor2: 'var(--gray-2)',
        grayColor3: 'var(--gray-3)',
        grayColor4: 'var(--gray-4)',
        lightGray: 'var(--light-gray)',
        lightGray2: 'var(--light-gray-2)',
        darkGray: 'var(--dark-gray)',
        lightPink: 'var(--light-pink)',
        lightBlue: 'var(--light-blue)',
        darkPink: 'var(--dark-pink)',
        colorGreen: 'var(--green)',
        colorOrange: 'var(--orange)',
        colorDarkOrange: 'var(--dark-orange)',
        colorYellow: 'var(--yellow)',
        colorPlaceholder: 'var(--placeholder)',
        gradientColorPrimary: 'var(--gradient-primary)',
        gradientColor2: 'var(--gradient-2)',
      },

      fontFamily: {
        fontLight: 'var(--font-light)',
        fontRegular: 'var(--font-regular)',
        fontMedium: 'var(--font-medium)',
        fontSemiBold: 'var(--font-semibold)',
        fontBold: 'var(--font-Bold)',
        fontExtraBold: 'var(--font-extrabold)',
        fontIBM: 'var(--font-IBM)',
      },
    },
  },
  plugins: [],
};
